"""Emit the lexeme bank as a SQL dump for Cloudflare D1.

The web viewer's bundled ``lexemes.json`` is the *join* of two pipeline
outputs — ``lexeme_bank.json`` (the canonical 語彙素 records) and
``crosswalk.tsv`` (every dictionary's attestation of each lexeme). This
exporter performs the same join (see ``web/scripts/sync-database.mjs``) and
materialises one ``lexemes`` table so the viewer can read lexemes from D1 in
production — exactly the way ``entries`` is served for the morpheme bank.

One ``lexemes`` table, JSON columns for the structured fields (D1 ships the
SQLite ``JSON1`` extension, so they stay queryable). The emitted attestation
shape is byte-for-byte the one the JS sync writes, so the D1 path and the
bundled-JSON fallback produce identical ``Lexeme`` objects.

Usage::

    uv run python -m lexeme_db.export_sqlite \
        --bank      lexeme_db/output/lexeme_bank.json \
        --crosswalk lexeme_db/output/crosswalk.tsv \
        --output    lexeme_db/output/lexemes.sql

Import into the (same) freshly-created D1 database, after the morpheme dump::

    wrangler d1 execute <db-name> --remote --file=lexeme_db/output/lexemes.sql
"""

from __future__ import annotations

import argparse
import csv
import datetime as _dt
import json
from collections import defaultdict
from pathlib import Path
from typing import Any

from lexeme_db.schema import Lexeme, load_lexemes

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = REPO_ROOT / "lexeme_db" / "output"
DEFAULT_BANK = OUTPUT_DIR / "lexeme_bank.json"
DEFAULT_CROSSWALK = OUTPUT_DIR / "crosswalk.tsv"
DEFAULT_OUTPUT = OUTPUT_DIR / "lexemes.sql"
DEFAULT_MORPHEMES = REPO_ROOT / "morpheme_db" / "output" / "morpheme_database.json"

# Keep this in sync with GLOSS_PREVIEW_CHARS in web/scripts/sync-database.mjs:
# the crosswalk keeps each source's full definition (megabytes); the viewer
# only needs a short preview, which keeps the D1 row / Worker payload small.
GLOSS_PREVIEW_CHARS = 160


SCHEMA = """\
-- Auto-generated by lexeme_db/export_sqlite.py. Do not edit by hand.
-- Schema version: 2

DROP TABLE IF EXISTS lexemes;

CREATE TABLE lexemes (
    id              TEXT PRIMARY KEY,
    lemma           TEXT NOT NULL,
    kana            TEXT NOT NULL DEFAULT '',
    pos             TEXT NOT NULL DEFAULT '',
    gloss_jp        TEXT NOT NULL DEFAULT '[]',
    gloss_en        TEXT NOT NULL DEFAULT '[]',
    bound           INTEGER NOT NULL DEFAULT 0,
    dialect_base    TEXT NOT NULL DEFAULT '',
    morphemes       TEXT NOT NULL DEFAULT '[]',
    senses          TEXT NOT NULL DEFAULT '[]',
    sources         TEXT NOT NULL DEFAULT '[]',
    notes           TEXT NOT NULL DEFAULT '',
    attestations    TEXT NOT NULL DEFAULT '[]',
    dialects        TEXT NOT NULL DEFAULT '[]',
    recordings      INTEGER NOT NULL DEFAULT 0,
    composition     TEXT NOT NULL DEFAULT '[]'
);

CREATE INDEX idx_lexemes_lemma ON lexemes(lemma);

CREATE TABLE IF NOT EXISTS db_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
"""


def _quote(value: str) -> str:
    """SQLite literal quoting — doubles single quotes."""
    return "'" + value.replace("'", "''") + "'"


def _json_field(payload: Any) -> str:
    return _quote(json.dumps(payload, ensure_ascii=False, separators=(",", ":")))


def load_crosswalk(path: Path) -> dict[str, list[dict[str, Any]]]:
    """Join key: lexeme_id → list of viewer-shaped attestation dicts.

    Mirrors ``parseCrosswalk`` in ``web/scripts/sync-database.mjs`` — same
    field names, same ``gloss`` preview cap, ``confidence`` as a number.
    """
    by_lexeme: dict[str, list[dict[str, Any]]] = defaultdict(list)
    if not path.exists():
        return by_lexeme
    with path.open(encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        for row in reader:
            lexeme_id = row.get("lexeme_id") or ""
            if not lexeme_id:
                continue
            try:
                confidence = float(row.get("confidence") or 0)
            except ValueError:
                confidence = 0.0
            by_lexeme[lexeme_id].append(
                {
                    "source": row.get("source", ""),
                    "dialect": row.get("dialect", ""),
                    "entry_ref": row.get("entry_ref", ""),
                    "surface_latn": row.get("surface_latn", ""),
                    "surface_kana": row.get("surface_kana", ""),
                    "pos_raw": row.get("pos_raw", ""),
                    "sense_id": row.get("sense_id", ""),
                    "match_kind": row.get("match_kind", ""),
                    "confidence": confidence,
                    "gloss": (row.get("gloss_raw") or "")[:GLOSS_PREVIEW_CHARS],
                }
            )
    return by_lexeme


def build_composition_resolver(morphemes_path: Path):
    """Resolve a lexeme's single morpheme link through to that morpheme's
    ``composition`` (the real multi-morpheme breakdown, inkar -> i- + nukar),
    flatten nested bracketing, and map ids to display lemmas. Mirrors
    ``buildCompositionResolver`` in ``web/scripts/sync-database.mjs``. Returns a
    callable; ``() -> []`` when the morpheme source is absent.
    """
    if not morphemes_path.exists():
        return lambda _ids: []
    entries = json.loads(morphemes_path.read_text(encoding="utf-8"))
    by_id = {e["id"]: e for e in entries}

    def flatten(comp: list[Any]) -> list[str]:
        out: list[str] = []
        for item in comp:
            if isinstance(item, list):
                out.extend(flatten(item))
            else:
                out.append(str(item))
        return out

    def resolve(morpheme_ids: list[str]) -> list[str]:
        entry = by_id.get(morpheme_ids[0]) if morpheme_ids else None
        comp = (entry or {}).get("composition") or []
        if len(comp) > 1:
            return [by_id.get(i, {}).get("lemma", i) for i in flatten(comp)]
        return []

    return resolve


def _lexeme_to_row(
    lx: Lexeme, attestations: list[dict[str, Any]], composition: list[str]
) -> str:
    dialects = sorted({a["dialect"] for a in attestations if a["dialect"]})
    senses = [s.to_dict() for s in lx.senses]
    return (
        "INSERT INTO lexemes VALUES ("
        f"{_quote(lx.id)},"
        f"{_quote(lx.lemma)},"
        f"{_quote(lx.kana)},"
        f"{_quote(lx.pos)},"
        f"{_json_field(lx.gloss_jp)},"
        f"{_json_field(lx.gloss_en)},"
        f"{1 if lx.bound else 0},"
        f"{_quote(lx.dialect_base)},"
        f"{_json_field(lx.morphemes)},"
        f"{_json_field(senses)},"
        f"{_json_field(lx.sources)},"
        f"{_quote(lx.notes)},"
        f"{_json_field(attestations)},"
        f"{_json_field(dialects)},"
        f"{len(attestations)},"
        f"{_json_field(composition)}"
        ");"
    )


def export(
    lexemes: list[Lexeme],
    crosswalk: dict[str, list[dict[str, Any]]],
    composition_of,
    schema_version: str,
    built_at: str,
) -> str:
    # As with the morpheme dump: no explicit BEGIN/SAVEPOINT — wrangler's
    # remote import batches the statements in its own managed transaction.
    lines: list[str] = [SCHEMA]
    total_recordings = 0
    for lx in lexemes:
        atts = crosswalk.get(lx.id, [])
        total_recordings += len(atts)
        lines.append(_lexeme_to_row(lx, atts, composition_of(lx.morphemes)))
    lines.append(
        f"INSERT OR REPLACE INTO db_meta(key, value) VALUES "
        f"({_quote('lexeme_schema_version')}, {_quote(schema_version)}),"
        f"({_quote('lexeme_built_at')}, {_quote(built_at)}),"
        f"({_quote('lexeme_count')}, {_quote(str(len(lexemes)))}),"
        f"({_quote('lexeme_recordings')}, {_quote(str(total_recordings))});"
    )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bank", type=Path, default=DEFAULT_BANK)
    parser.add_argument("--crosswalk", type=Path, default=DEFAULT_CROSSWALK)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--morphemes", type=Path, default=DEFAULT_MORPHEMES)
    parser.add_argument("--schema-version", default="2")
    args = parser.parse_args(argv)

    lexemes = load_lexemes(args.bank)
    crosswalk = load_crosswalk(args.crosswalk)
    composition_of = build_composition_resolver(args.morphemes)
    sql = export(
        lexemes,
        crosswalk,
        composition_of,
        schema_version=args.schema_version,
        built_at=_dt.datetime.now(_dt.UTC).isoformat(timespec="seconds"),
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql, encoding="utf-8")
    size_kb = args.output.stat().st_size / 1024
    recordings = sum(len(v) for v in crosswalk.values())
    print(
        f"Wrote {len(lexemes)} lexemes ({recordings} recordings) → "
        f"{args.output} ({size_kb:.1f} KB) schema_version={args.schema_version}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
