"""Emit the morpheme database as a SQL dump for Cloudflare D1.

D1 = managed SQLite. We materialise one ``entries`` table that uses JSON
columns for the structured fields (slots, rules, allomorphs, etc.) — D1
supports the SQLite ``JSON1`` extension so this remains queryable, while
keeping schema migrations trivial as the dataclasses evolve.

Usage::

    uv run python -m morpheme_db.export_sqlite \
        --input  morpheme_db/output/morpheme_database.json \
        --output morpheme_db/output/morpheme_database.sql

Import into a freshly-created D1 database::

    wrangler d1 create ainu-mdb-$(date -u +%Y%m%d-%H%M)
    wrangler d1 execute <db-name> --remote --file=morpheme_db/output/morpheme_database.sql
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from morpheme_db.schema import Entry, load_entries

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = REPO_ROOT / "morpheme_db" / "output" / "morpheme_database.json"
DEFAULT_OUTPUT = REPO_ROOT / "morpheme_db" / "output" / "morpheme_database.sql"


SCHEMA = """\
-- Auto-generated by morpheme_db/export_sqlite.py. Do not edit by hand.
-- Schema version: 3

DROP TABLE IF EXISTS entries;

CREATE TABLE entries (
    id                    TEXT PRIMARY KEY,
    lemma                 TEXT NOT NULL,
    allomorphs            TEXT NOT NULL DEFAULT '[]',
    category              TEXT NOT NULL DEFAULT '',
    category_alt          TEXT NOT NULL DEFAULT '[]',
    bound                 INTEGER NOT NULL DEFAULT 0,
    morph_type            TEXT NOT NULL DEFAULT 'root',
    slot                  TEXT NOT NULL DEFAULT '[]',
    base_frame            TEXT,
    rules                 TEXT NOT NULL DEFAULT '[]',
    attaches_to           TEXT NOT NULL DEFAULT '[]',
    selection             TEXT NOT NULL DEFAULT '[]',
    glosses_en            TEXT NOT NULL DEFAULT '[]',
    glosses_jp            TEXT NOT NULL DEFAULT '[]',
    dialects              TEXT NOT NULL DEFAULT '[]',
    sources               TEXT NOT NULL DEFAULT '[]',
    notes                 TEXT NOT NULL DEFAULT '',
    frequency             INTEGER NOT NULL DEFAULT 0,
    verified              INTEGER NOT NULL DEFAULT 0,
    composition           TEXT NOT NULL DEFAULT '[]',
    composition_surface   TEXT NOT NULL DEFAULT '[]',
    composition_note      TEXT NOT NULL DEFAULT '',
    reconstructed         TEXT NOT NULL DEFAULT '{}',
    etymology             TEXT
);

CREATE INDEX idx_entries_lemma ON entries(lemma);
CREATE INDEX idx_entries_verified_freq ON entries(verified DESC, frequency DESC);

CREATE TABLE IF NOT EXISTS db_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
"""


def _quote(value: str) -> str:
    """SQLite literal quoting — doubles single quotes."""
    return "'" + value.replace("'", "''") + "'"


def _json_field(payload) -> str:  # type: ignore[no-untyped-def]
    return _quote(json.dumps(payload, ensure_ascii=False, separators=(",", ":")))


def _entry_to_row(entry: Entry) -> str:
    base_frame_sql = (
        _quote(json.dumps(entry.base_frame.to_dict(), ensure_ascii=False, separators=(",", ":")))
        if entry.base_frame is not None
        else "NULL"
    )
    rules_payload = [r.to_dict() for r in entry.rules]
    etymology_sql = _quote(json.dumps(entry.etymology, ensure_ascii=False, separators=(",", ":"))) if entry.etymology is not None else "NULL"
    return (
        "INSERT INTO entries VALUES ("
        f"{_quote(entry.id)},"
        f"{_quote(entry.lemma)},"
        f"{_json_field(entry.allomorphs)},"
        f"{_quote(entry.category)},"
        f"{_json_field(entry.category_alt)},"
        f"{1 if entry.bound else 0},"
        f"{_quote(entry.morph_type)},"
        f"{_json_field(entry.slot)},"
        f"{base_frame_sql},"
        f"{_json_field(rules_payload)},"
        f"{_json_field(entry.attaches_to)},"
        f"{_json_field(entry.selection)},"
        f"{_json_field(entry.glosses_en)},"
        f"{_json_field(entry.glosses_jp)},"
        f"{_json_field(entry.dialects)},"
        f"{_json_field(entry.sources)},"
        f"{_quote(entry.notes)},"
        f"{entry.frequency},"
        f"{1 if entry.verified else 0},"
        f"{_json_field(entry.composition)},"
        f"{_json_field(entry.composition_surface)},"
        f"{_quote(entry.composition_note)},"
        f"{_json_field(entry.reconstructed)},"
        f"{etymology_sql}"
        ");"
    )


def export(entries: list[Entry], schema_version: str, built_at: str) -> str:
    # D1's remote import (wrangler ≥4.91) rejects explicit ``BEGIN
    # TRANSACTION`` / ``SAVEPOINT`` statements — the import API batches the
    # statements itself and runs them in a managed transaction. We emit a
    # plain sequence of DDL + INSERTs and let wrangler handle atomicity.
    lines: list[str] = [SCHEMA]
    lines.append(
        f"INSERT OR REPLACE INTO db_meta(key, value) VALUES "
        f"({_quote('schema_version')}, {_quote(schema_version)}),"
        f"({_quote('built_at')}, {_quote(built_at)}),"
        f"({_quote('entry_count')}, {_quote(str(len(entries)))});"
    )
    for entry in entries:
        lines.append(_entry_to_row(entry))
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--schema-version",
        default="3",
        help="Schema version stamp written into db_meta.",
    )
    args = parser.parse_args(argv)

    import datetime as _dt

    entries = load_entries(args.input)
    sql = export(
        entries,
        schema_version=args.schema_version,
        built_at=_dt.datetime.now(_dt.UTC).isoformat(timespec="seconds"),
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql, encoding="utf-8")
    size_kb = args.output.stat().st_size / 1024
    print(
        f"Wrote {len(entries)} entries → {args.output} ({size_kb:.1f} KB) "
        f"schema_version={args.schema_version}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
